name: flutter_boilerplate
description: A Template Project for Flutter.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  pretty_dio_logger: ^1.2.0-beta-1
  easy_refresh: ^3.0.4+1
  trending_common:
    path: packages/trending_common
  trending_api:
    path: packages/trending_api
  dio_trending_api:
    path: packages/dio_trending_api
  trending_repository_middleware:
    path: packages/trending_repository_middleware
  local_storage_trending_repository_middleware:
    path: packages/local_storage_trending_repository_middleware
  trending_repository:
    path: packages/trending_repository

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
