on:
  # Enable manual run
  workflow_dispatch:
    inputs:
      version:
        description: "Tag to create (e.g. v2.10.0). Must include 'v' and must match pubspec"
        required: true
        default: "v2.10.0"
        type: string
      flavor:
        type: choice
        description: "Which flavor are you using?"
        required: true
        default: "development"
        options:
          - development
          - staging
          - production

name: Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: 'r21e'
          add-to-path: true
        env:
          ANDROID_NDK_HOME: '/usr/local/lib/android/sdk/ndk'

      - name: Flutter doctor -v
        run: flutter doctor -v

      - name: Install Deps
        run: flutter pub get

      - name: Configure Dev Keystore
        if: github.event.inputs.flavor == 'development'
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/flutter_boilerplate.jks
          echo "storeFile=flutter_boilerplate.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY_DEV }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS_DEV }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD_DEV }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD_DEV }}
        working-directory: android

      - name: Configure Stg Keystore
        if: github.event.inputs.flavor == 'staging'
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/flutter_boilerplate.jks
          echo "storeFile=flutter_boilerplate.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY_STG }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS_STG }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD_STG }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD_STG }}
        working-directory: android

      - name: Configure Prod Keystore
        if: github.event.inputs.flavor == 'production'
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/flutter_boilerplate.jks
          echo "storeFile=flutter_boilerplate.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        working-directory: android

      - name: Build APKs
        run: flutter build apk --split-per-abi --no-tree-shake-icons --flavor ${{ github.event.inputs.flavor }} --target lib/main_${{ github.event.inputs.flavor }}.dart

      - name: Build Appbundle
        run: flutter build appbundle  --no-tree-shake-icons --flavor ${{ github.event.inputs.flavor }} --target lib/main_${{ github.event.inputs.flavor }}.dart

      - name: Push APK to Releases
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.event.inputs.version }}_${{ github.event.inputs.flavor }}
          artifacts: "build/app/outputs/flutter-apk/*.apk,build/app/outputs/bundle/${{ github.event.inputs.flavor }}Release/*.aab"
          tag: ${{ github.event.inputs.version }}
          token: ${{ secrets.TOKEN }}
          prerelease: ${{ github.event.inputs.flavor != "production" }}
